<a href="https://colab.research.google.com/github/CuiyingLin17/IS477BusinessCoders/blob/main/acquire_CPIAUCSL_assess1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import os
import requests
import hashlib
os.makedirs("data/raw", exist_ok=True)

CPIAUCSL_url = "https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23ebf3fb&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=1320&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=CPIAUCSL&scale=left&cosd=1947-01-01&coed=2026-02-01&line_color=%230073e6&link_values=false&line_style=solid&mark_type=none&mw=3&lw=3&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2026-04-05&revision_date=2026-04-05&nd=1947-01-01"
CPIAUCSL_filename = "CPIAUCSL.csv"

response = requests.get(CPIAUCSL_url)

with open(CPIAUCSL_filename, "wb") as f:
    f.write(response.content)

print("Saved CPIAUCSL dataset:", CPIAUCSL_filename)

def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

print("UNRATE SHA-256:", sha256(CPIAUCSL_filename))

import pandas as pd
df = pd.read_csv(CPIAUCSL_filename)
df.head()

Saved CPIAUCSL dataset: CPIAUCSL.csv
UNRATE SHA-256: 4494d9e15555069f0721bf5d18062bd7f88b70e3736ac5da2d5fcaf9ac64cd40

  observation_date  CPIAUCSL
0       1947-01-01     21.48
1       1947-02-01     21.62
2       1947-03-01     22.00
3       1947-04-01     22.00
4       1947-05-01     21.95

In [16]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)

Shape: (950, 2)
Columns: ['observation_date', 'CPIAUCSL']

Data types:
observation_date     object
CPIAUCSL            float64
dtype: object

In [17]:
print("Missing values:")
print(df.isna().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
observation_date    0
CPIAUCSL            1
dtype: int64

Duplicate rows: 0

In [18]:

df[df.columns[0]] = pd.to_datetime(df[df.columns[0]], errors="coerce")
print("Date range:", df[df.columns[0]].min(), "to", df[df.columns[0]].max())

Date range: 1947-01-01 00:00:00 to 2026-02-01 00:00:00

In [21]:
df['OLD_CPI'] = df['CPIAUCSL'].shift(1)
df['Inflation_Rate'] = (df['CPIAUCSL'] - df['OLD_CPI']) / df['OLD_CPI'] * 100
df = df.drop(columns=['OLD_CPI'])

In [22]:
df.head()

  observation_date  CPIAUCSL  Inflation_Rate
0       1947-01-01     21.48             NaN
1       1947-02-01     21.62        0.651769
2       1947-03-01     22.00        1.757632
3       1947-04-01     22.00        0.000000
4       1947-05-01     21.95       -0.227273